Add audio adc labview plugin with ac and frequency response measurements
NI-MeasurementLink-Plug-Ins/audio-adc-labview pull request #1
Opened 2024-02-27 16:56 UTC by SJayaraman-NI

- Update README.md, github files and other docs
- Add source code of measurements AC and Frequency Response
- Add NIPM package build spec for the plugin
- Tested the package with the hardware setup with two different DUTs

2024-02-27 17:07 UTC, SJayaraman-NI commented
@jarnoldNI Could you review this PR to merge the commit to the 'NI-MeasurementLink-Plug-Ins : main' branch?

2024-02-29 06:24 UTC, Upatel-NI requested changes

2024-02-29 06:24 UTC, Upatel-NI commented on README.md
> +![image](res/audio-adc-plugin.png)
please add correct results frequency displayed in result table is wrong. Sample rate used is wrong and it leads to incorrect graph as well

2024-02-29 06:24 UTC, Upatel-NI commented on README.md
> +   - Output power
We don't have output power measured

2024-02-29 06:24 UTC, Upatel-NI commented on README.md
> +## Hardware Setup
We can add this line as user will understand SMU is not dependency **(note: the software does not use the SMU/power supply but need something to power the DUT)** I will keep it to u where to put it

2024-02-29 06:24 UTC, Upatel-NI commented on docs/help.md
> +
Measurements are not correct

2024-03-05 14:52 UTC, inmeyyav commented on README.md
> +'Audio ADC - LabVIEW' is a MeasurementLink based plugin that enables users to perform measurements of Audio Analog to Digital Converters.
Rephrase as "Audio ADC - LabVIEW" is a MeasurementLink LabVIEW plugin for making measurements for Audio ADC's

2024-03-05 14:55 UTC, inmeyyav commented on README.md
> +The measurement plugin generate an analog audio signal input to the Device Under Test and measures the Digital Output.
Rephrase as "This plugin generates analog signal and measures the digital audio output of the ADC".
FYI: We are not generating Audio signal, we are acquiring audio signal.

2024-03-21 07:55 UTC, inmeyyav approved these changes

2024-03-21 08:07 UTC, SJayaraman-NI commented
[like]  Srinivasan J reacted to your message:
________________________________
From: inmeyyav ***@***.***>
Sent: Thursday, March 21, 2024 7:55:40 AM
To: NI-MeasurementLink-Plug-Ins/audio-adc-labview ***@***.***>
Cc: Srinivasan J ***@***.***>; Author ***@***.***>
Subject: Re: [NI-MeasurementLink-Plug-Ins/audio-adc-labview] Add audio adc labview plugin with ac and frequency response measurements (PR #1)

You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@inmeyyav approved this pull request.

—
Reply to this email directly, view it on GitHub<https://github.com/NI-MeasurementLink-Plug-Ins/audio-adc-labview/pull/1#pullrequestreview-1951041149>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BFSCXCPYNUNZIEU2CS6PPDDYZKG7ZAVCNFSM6AAAAABD4PGSL2VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSNJRGA2DCMJUHE>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-03-25 13:00 UTC, Kbhava requested changes
rename the vi without underscore

2024-03-25 13:00 UTC, Kbhava commented on docs/software-development.md
> +The files can be found at this [link](https://github.com/ni/measurementlink-labview/releases/tag/v1.0.1).
Class D amplifier uses 2023 Q4 version, same as PMIC, should we update the the measurement link version and their dependency https://github.com/ni/measurementlink-labview/releases/tag/v1.2.0.4.

2024-03-26 06:18 UTC, Kbhava approved these changes

2024-03-26 11:32 UTC, merged